name: learn-github-actions-4
run-name: ${{ github.actor }} is learning GitHub  4(Env)
on: [push]
jobs:
  Check-Bat-Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Echo Env Var
        env:
           NODE_VER: 16
        run: echo "Value of Env is $NODE_VER"

      - name: "Dump Secret Value From Secret Config"
        env:
          SECRETS_VARS: ${{ toJson(secrets) }}
        run: echo "$SECRETS_VARS"
      
      - name: Dump Secret Env variables from env config 1
        env:
          API_KEY_XX: ${{ secrets.API_KEY_XX}}
        run: echo "Value of home url is $API_KEY_XX"
      
      - name: Dump Secret Env variables from env config 2
        env:
          API_KEY_YYY: ${{ secrets.API_KEY_YYY}}
        run: echo "Value of home url is $API_KEY_YYY"
      
      - name: Dump Context 
        run: echo "$GITHUB_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
      
